/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AppRouteImport } from './routes/app'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as AuthenticatedEntregadorRouteImport } from './routes/_authenticated/entregador'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as EntregadorLoginRouteImport } from './routes/entregador.login'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as AuthenticatedLojaIndexRouteImport } from './routes/_authenticated/loja.index'
import { Route as AuthenticatedLojaChatRouteImport } from './routes/_authenticated/loja.chat'
import { Route as AuthenticatedLojaConfigRouteImport } from './routes/_authenticated/loja.config'
import { Route as AuthenticatedLojaDashboardRouteImport } from './routes/_authenticated/loja.dashboard'
import { Route as AuthenticatedLojaEntregadoresRouteImport } from './routes/_authenticated/loja.entregadores'
import { Route as AuthenticatedLojaFinanceiroRouteImport } from './routes/_authenticated/loja.financeiro'
import { Route as AuthenticatedLojaFreteRouteImport } from './routes/_authenticated/loja.frete'
import { Route as AuthenticatedLojaLeadsRouteImport } from './routes/_authenticated/loja.leads'
import { Route as AuthenticatedLojaLogsRouteImport } from './routes/_authenticated/loja.logs'
import { Route as AuthenticatedLojaPedidosRouteImport } from './routes/_authenticated/loja.pedidos'
import { Route as AuthenticatedLojaPrecificacaoRouteImport } from './routes/_authenticated/loja.precificacao'
import { Route as AuthenticatedLojaProdutosRouteImport } from './routes/_authenticated/loja.produtos'
import { Route as AuthenticatedLojaReceberRouteImport } from './routes/_authenticated/loja.receber'
import { Route as AuthenticatedLojaZonasEntregaRouteImport } from './routes/_authenticated/loja.zonas-entrega'
import { Route as AuthenticatedLojaPedidoIdRouteImport } from './routes/_authenticated/loja.pedido.$id'
import { Route as ApiPublicHooksSystemAlertsRouteImport } from './routes/api/public/hooks/system-alerts'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks.evolution'
import { Route as ApiPublicWebhooksIfoodRouteImport } from './routes/api/public/webhooks.ifood'
import { Route as ApiPublicWebhooksIfoodPollRouteImport } from './routes/api/public/webhooks.ifood-poll'
import { Route as ApiPublicWebhooksIfoodStatusPushRouteImport } from './routes/api/public/webhooks.ifood-status-push'
import { Route as ApiPublicWebhooksMetaRouteImport } from './routes/api/public/webhooks.meta'
import { Route as ApiPublicWebhooksNfoodRouteImport } from './routes/api/public/webhooks.nfood'
import { Route as ApiPublicWebhooksNfoodStatusPushRouteImport } from './routes/api/public/webhooks.nfood-status-push'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks.stripe'
import { Route as ApiPublicWebhooksWhatsappNotifyRouteImport } from './routes/api/public/webhooks.whatsapp-notify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEntregadorRoute = AuthenticatedEntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorLoginRoute = EntregadorLoginRouteImport.update({
  id: '/entregador/login',
  path: '/entregador/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLojaIndexRoute = AuthenticatedLojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaChatRoute = AuthenticatedLojaChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaConfigRoute = AuthenticatedLojaConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaDashboardRoute =
  AuthenticatedLojaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaEntregadoresRoute =
  AuthenticatedLojaEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaFinanceiroRoute =
  AuthenticatedLojaFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaFreteRoute = AuthenticatedLojaFreteRouteImport.update({
  id: '/frete',
  path: '/frete',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaLeadsRoute = AuthenticatedLojaLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaLogsRoute = AuthenticatedLojaLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaPedidosRoute =
  AuthenticatedLojaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaPrecificacaoRoute =
  AuthenticatedLojaPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaProdutosRoute =
  AuthenticatedLojaProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaReceberRoute =
  AuthenticatedLojaReceberRouteImport.update({
    id: '/receber',
    path: '/receber',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaZonasEntregaRoute =
  AuthenticatedLojaZonasEntregaRouteImport.update({
    id: '/zonas-entrega',
    path: '/zonas-entrega',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaPedidoIdRoute =
  AuthenticatedLojaPedidoIdRouteImport.update({
    id: '/pedido/$id',
    path: '/pedido/$id',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const ApiPublicHooksSystemAlertsRoute =
  ApiPublicHooksSystemAlertsRouteImport.update({
    id: '/api/public/hooks/system-alerts',
    path: '/api/public/hooks/system-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksIfoodRoute = ApiPublicWebhooksIfoodRouteImport.update({
  id: '/api/public/webhooks/ifood',
  path: '/api/public/webhooks/ifood',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksIfoodPollRoute =
  ApiPublicWebhooksIfoodPollRouteImport.update({
    id: '/api/public/webhooks/ifood-poll',
    path: '/api/public/webhooks/ifood-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksIfoodStatusPushRoute =
  ApiPublicWebhooksIfoodStatusPushRouteImport.update({
    id: '/api/public/webhooks/ifood-status-push',
    path: '/api/public/webhooks/ifood-status-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMetaRoute = ApiPublicWebhooksMetaRouteImport.update({
  id: '/api/public/webhooks/meta',
  path: '/api/public/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksNfoodRoute = ApiPublicWebhooksNfoodRouteImport.update({
  id: '/api/public/webhooks/nfood',
  path: '/api/public/webhooks/nfood',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksNfoodStatusPushRoute =
  ApiPublicWebhooksNfoodStatusPushRouteImport.update({
    id: '/api/public/webhooks/nfood-status-push',
    path: '/api/public/webhooks/nfood-status-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWhatsappNotifyRoute =
  ApiPublicWebhooksWhatsappNotifyRouteImport.update({
    id: '/api/public/webhooks/whatsapp-notify',
    path: '/api/public/webhooks/whatsapp-notify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/loja': typeof AuthenticatedLojaRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/entregador/login': typeof EntregadorLoginRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/loja/chat': typeof AuthenticatedLojaChatRoute
  '/loja/config': typeof AuthenticatedLojaConfigRoute
  '/loja/dashboard': typeof AuthenticatedLojaDashboardRoute
  '/loja/entregadores': typeof AuthenticatedLojaEntregadoresRoute
  '/loja/financeiro': typeof AuthenticatedLojaFinanceiroRoute
  '/loja/frete': typeof AuthenticatedLojaFreteRoute
  '/loja/leads': typeof AuthenticatedLojaLeadsRoute
  '/loja/logs': typeof AuthenticatedLojaLogsRoute
  '/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/loja/precificacao': typeof AuthenticatedLojaPrecificacaoRoute
  '/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/loja/receber': typeof AuthenticatedLojaReceberRoute
  '/loja/zonas-entrega': typeof AuthenticatedLojaZonasEntregaRoute
  '/loja/': typeof AuthenticatedLojaIndexRoute
  '/loja/pedido/$id': typeof AuthenticatedLojaPedidoIdRoute
  '/api/public/hooks/system-alerts': typeof ApiPublicHooksSystemAlertsRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/ifood': typeof ApiPublicWebhooksIfoodRoute
  '/api/public/webhooks/ifood-poll': typeof ApiPublicWebhooksIfoodPollRoute
  '/api/public/webhooks/ifood-status-push': typeof ApiPublicWebhooksIfoodStatusPushRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/public/webhooks/nfood': typeof ApiPublicWebhooksNfoodRoute
  '/api/public/webhooks/nfood-status-push': typeof ApiPublicWebhooksNfoodStatusPushRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp-notify': typeof ApiPublicWebhooksWhatsappNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/admin/login': typeof AdminLoginRoute
  '/entregador/login': typeof EntregadorLoginRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/loja/chat': typeof AuthenticatedLojaChatRoute
  '/loja/config': typeof AuthenticatedLojaConfigRoute
  '/loja/dashboard': typeof AuthenticatedLojaDashboardRoute
  '/loja/entregadores': typeof AuthenticatedLojaEntregadoresRoute
  '/loja/financeiro': typeof AuthenticatedLojaFinanceiroRoute
  '/loja/frete': typeof AuthenticatedLojaFreteRoute
  '/loja/leads': typeof AuthenticatedLojaLeadsRoute
  '/loja/logs': typeof AuthenticatedLojaLogsRoute
  '/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/loja/precificacao': typeof AuthenticatedLojaPrecificacaoRoute
  '/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/loja/receber': typeof AuthenticatedLojaReceberRoute
  '/loja/zonas-entrega': typeof AuthenticatedLojaZonasEntregaRoute
  '/loja': typeof AuthenticatedLojaIndexRoute
  '/loja/pedido/$id': typeof AuthenticatedLojaPedidoIdRoute
  '/api/public/hooks/system-alerts': typeof ApiPublicHooksSystemAlertsRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/ifood': typeof ApiPublicWebhooksIfoodRoute
  '/api/public/webhooks/ifood-poll': typeof ApiPublicWebhooksIfoodPollRoute
  '/api/public/webhooks/ifood-status-push': typeof ApiPublicWebhooksIfoodStatusPushRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/public/webhooks/nfood': typeof ApiPublicWebhooksNfoodRoute
  '/api/public/webhooks/nfood-status-push': typeof ApiPublicWebhooksNfoodStatusPushRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp-notify': typeof ApiPublicWebhooksWhatsappNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/_authenticated/entregador': typeof AuthenticatedEntregadorRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/entregador/login': typeof EntregadorLoginRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/_authenticated/loja/chat': typeof AuthenticatedLojaChatRoute
  '/_authenticated/loja/config': typeof AuthenticatedLojaConfigRoute
  '/_authenticated/loja/dashboard': typeof AuthenticatedLojaDashboardRoute
  '/_authenticated/loja/entregadores': typeof AuthenticatedLojaEntregadoresRoute
  '/_authenticated/loja/financeiro': typeof AuthenticatedLojaFinanceiroRoute
  '/_authenticated/loja/frete': typeof AuthenticatedLojaFreteRoute
  '/_authenticated/loja/leads': typeof AuthenticatedLojaLeadsRoute
  '/_authenticated/loja/logs': typeof AuthenticatedLojaLogsRoute
  '/_authenticated/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/_authenticated/loja/precificacao': typeof AuthenticatedLojaPrecificacaoRoute
  '/_authenticated/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/_authenticated/loja/receber': typeof AuthenticatedLojaReceberRoute
  '/_authenticated/loja/zonas-entrega': typeof AuthenticatedLojaZonasEntregaRoute
  '/_authenticated/loja/': typeof AuthenticatedLojaIndexRoute
  '/_authenticated/loja/pedido/$id': typeof AuthenticatedLojaPedidoIdRoute
  '/api/public/hooks/system-alerts': typeof ApiPublicHooksSystemAlertsRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/ifood': typeof ApiPublicWebhooksIfoodRoute
  '/api/public/webhooks/ifood-poll': typeof ApiPublicWebhooksIfoodPollRoute
  '/api/public/webhooks/ifood-status-push': typeof ApiPublicWebhooksIfoodStatusPushRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/public/webhooks/nfood': typeof ApiPublicWebhooksNfoodRoute
  '/api/public/webhooks/nfood-status-push': typeof ApiPublicWebhooksNfoodStatusPushRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp-notify': typeof ApiPublicWebhooksWhatsappNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/meus-pedidos'
    | '/politica-de-privacidade'
    | '/entregador'
    | '/loja'
    | '/admin/login'
    | '/entregador/login'
    | '/pedido/$id'
    | '/loja/chat'
    | '/loja/config'
    | '/loja/dashboard'
    | '/loja/entregadores'
    | '/loja/financeiro'
    | '/loja/frete'
    | '/loja/leads'
    | '/loja/logs'
    | '/loja/pedidos'
    | '/loja/precificacao'
    | '/loja/produtos'
    | '/loja/receber'
    | '/loja/zonas-entrega'
    | '/loja/'
    | '/loja/pedido/$id'
    | '/api/public/hooks/system-alerts'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/ifood'
    | '/api/public/webhooks/ifood-poll'
    | '/api/public/webhooks/ifood-status-push'
    | '/api/public/webhooks/meta'
    | '/api/public/webhooks/nfood'
    | '/api/public/webhooks/nfood-status-push'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp-notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/meus-pedidos'
    | '/politica-de-privacidade'
    | '/entregador'
    | '/admin/login'
    | '/entregador/login'
    | '/pedido/$id'
    | '/loja/chat'
    | '/loja/config'
    | '/loja/dashboard'
    | '/loja/entregadores'
    | '/loja/financeiro'
    | '/loja/frete'
    | '/loja/leads'
    | '/loja/logs'
    | '/loja/pedidos'
    | '/loja/precificacao'
    | '/loja/produtos'
    | '/loja/receber'
    | '/loja/zonas-entrega'
    | '/loja'
    | '/loja/pedido/$id'
    | '/api/public/hooks/system-alerts'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/ifood'
    | '/api/public/webhooks/ifood-poll'
    | '/api/public/webhooks/ifood-status-push'
    | '/api/public/webhooks/meta'
    | '/api/public/webhooks/nfood'
    | '/api/public/webhooks/nfood-status-push'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp-notify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/meus-pedidos'
    | '/politica-de-privacidade'
    | '/_authenticated/entregador'
    | '/_authenticated/loja'
    | '/admin/login'
    | '/entregador/login'
    | '/pedido/$id'
    | '/_authenticated/loja/chat'
    | '/_authenticated/loja/config'
    | '/_authenticated/loja/dashboard'
    | '/_authenticated/loja/entregadores'
    | '/_authenticated/loja/financeiro'
    | '/_authenticated/loja/frete'
    | '/_authenticated/loja/leads'
    | '/_authenticated/loja/logs'
    | '/_authenticated/loja/pedidos'
    | '/_authenticated/loja/precificacao'
    | '/_authenticated/loja/produtos'
    | '/_authenticated/loja/receber'
    | '/_authenticated/loja/zonas-entrega'
    | '/_authenticated/loja/'
    | '/_authenticated/loja/pedido/$id'
    | '/api/public/hooks/system-alerts'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/ifood'
    | '/api/public/webhooks/ifood-poll'
    | '/api/public/webhooks/ifood-status-push'
    | '/api/public/webhooks/meta'
    | '/api/public/webhooks/nfood'
    | '/api/public/webhooks/nfood-status-push'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp-notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EntregadorLoginRoute: typeof EntregadorLoginRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ApiPublicHooksSystemAlertsRoute: typeof ApiPublicHooksSystemAlertsRoute
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRoute
  ApiPublicWebhooksIfoodRoute: typeof ApiPublicWebhooksIfoodRoute
  ApiPublicWebhooksIfoodPollRoute: typeof ApiPublicWebhooksIfoodPollRoute
  ApiPublicWebhooksIfoodStatusPushRoute: typeof ApiPublicWebhooksIfoodStatusPushRoute
  ApiPublicWebhooksMetaRoute: typeof ApiPublicWebhooksMetaRoute
  ApiPublicWebhooksNfoodRoute: typeof ApiPublicWebhooksNfoodRoute
  ApiPublicWebhooksNfoodStatusPushRoute: typeof ApiPublicWebhooksNfoodStatusPushRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicWebhooksWhatsappNotifyRoute: typeof ApiPublicWebhooksWhatsappNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/entregador': {
      id: '/_authenticated/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof AuthenticatedEntregadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador/login': {
      id: '/entregador/login'
      path: '/entregador/login'
      fullPath: '/entregador/login'
      preLoaderRoute: typeof EntregadorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loja/': {
      id: '/_authenticated/loja/'
      path: '/'
      fullPath: '/loja/'
      preLoaderRoute: typeof AuthenticatedLojaIndexRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/chat': {
      id: '/_authenticated/loja/chat'
      path: '/chat'
      fullPath: '/loja/chat'
      preLoaderRoute: typeof AuthenticatedLojaChatRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/config': {
      id: '/_authenticated/loja/config'
      path: '/config'
      fullPath: '/loja/config'
      preLoaderRoute: typeof AuthenticatedLojaConfigRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/dashboard': {
      id: '/_authenticated/loja/dashboard'
      path: '/dashboard'
      fullPath: '/loja/dashboard'
      preLoaderRoute: typeof AuthenticatedLojaDashboardRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/entregadores': {
      id: '/_authenticated/loja/entregadores'
      path: '/entregadores'
      fullPath: '/loja/entregadores'
      preLoaderRoute: typeof AuthenticatedLojaEntregadoresRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/financeiro': {
      id: '/_authenticated/loja/financeiro'
      path: '/financeiro'
      fullPath: '/loja/financeiro'
      preLoaderRoute: typeof AuthenticatedLojaFinanceiroRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/frete': {
      id: '/_authenticated/loja/frete'
      path: '/frete'
      fullPath: '/loja/frete'
      preLoaderRoute: typeof AuthenticatedLojaFreteRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/leads': {
      id: '/_authenticated/loja/leads'
      path: '/leads'
      fullPath: '/loja/leads'
      preLoaderRoute: typeof AuthenticatedLojaLeadsRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/logs': {
      id: '/_authenticated/loja/logs'
      path: '/logs'
      fullPath: '/loja/logs'
      preLoaderRoute: typeof AuthenticatedLojaLogsRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/pedidos': {
      id: '/_authenticated/loja/pedidos'
      path: '/pedidos'
      fullPath: '/loja/pedidos'
      preLoaderRoute: typeof AuthenticatedLojaPedidosRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/precificacao': {
      id: '/_authenticated/loja/precificacao'
      path: '/precificacao'
      fullPath: '/loja/precificacao'
      preLoaderRoute: typeof AuthenticatedLojaPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/produtos': {
      id: '/_authenticated/loja/produtos'
      path: '/produtos'
      fullPath: '/loja/produtos'
      preLoaderRoute: typeof AuthenticatedLojaProdutosRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/receber': {
      id: '/_authenticated/loja/receber'
      path: '/receber'
      fullPath: '/loja/receber'
      preLoaderRoute: typeof AuthenticatedLojaReceberRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/zonas-entrega': {
      id: '/_authenticated/loja/zonas-entrega'
      path: '/zonas-entrega'
      fullPath: '/loja/zonas-entrega'
      preLoaderRoute: typeof AuthenticatedLojaZonasEntregaRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/pedido/$id': {
      id: '/_authenticated/loja/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/loja/pedido/$id'
      preLoaderRoute: typeof AuthenticatedLojaPedidoIdRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/api/public/hooks/system-alerts': {
      id: '/api/public/hooks/system-alerts'
      path: '/api/public/hooks/system-alerts'
      fullPath: '/api/public/hooks/system-alerts'
      preLoaderRoute: typeof ApiPublicHooksSystemAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ifood': {
      id: '/api/public/webhooks/ifood'
      path: '/api/public/webhooks/ifood'
      fullPath: '/api/public/webhooks/ifood'
      preLoaderRoute: typeof ApiPublicWebhooksIfoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ifood-poll': {
      id: '/api/public/webhooks/ifood-poll'
      path: '/api/public/webhooks/ifood-poll'
      fullPath: '/api/public/webhooks/ifood-poll'
      preLoaderRoute: typeof ApiPublicWebhooksIfoodPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ifood-status-push': {
      id: '/api/public/webhooks/ifood-status-push'
      path: '/api/public/webhooks/ifood-status-push'
      fullPath: '/api/public/webhooks/ifood-status-push'
      preLoaderRoute: typeof ApiPublicWebhooksIfoodStatusPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta': {
      id: '/api/public/webhooks/meta'
      path: '/api/public/webhooks/meta'
      fullPath: '/api/public/webhooks/meta'
      preLoaderRoute: typeof ApiPublicWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nfood': {
      id: '/api/public/webhooks/nfood'
      path: '/api/public/webhooks/nfood'
      fullPath: '/api/public/webhooks/nfood'
      preLoaderRoute: typeof ApiPublicWebhooksNfoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nfood-status-push': {
      id: '/api/public/webhooks/nfood-status-push'
      path: '/api/public/webhooks/nfood-status-push'
      fullPath: '/api/public/webhooks/nfood-status-push'
      preLoaderRoute: typeof ApiPublicWebhooksNfoodStatusPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp-notify': {
      id: '/api/public/webhooks/whatsapp-notify'
      path: '/api/public/webhooks/whatsapp-notify'
      fullPath: '/api/public/webhooks/whatsapp-notify'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLojaRouteChildren {
  AuthenticatedLojaChatRoute: typeof AuthenticatedLojaChatRoute
  AuthenticatedLojaConfigRoute: typeof AuthenticatedLojaConfigRoute
  AuthenticatedLojaDashboardRoute: typeof AuthenticatedLojaDashboardRoute
  AuthenticatedLojaEntregadoresRoute: typeof AuthenticatedLojaEntregadoresRoute
  AuthenticatedLojaFinanceiroRoute: typeof AuthenticatedLojaFinanceiroRoute
  AuthenticatedLojaFreteRoute: typeof AuthenticatedLojaFreteRoute
  AuthenticatedLojaLeadsRoute: typeof AuthenticatedLojaLeadsRoute
  AuthenticatedLojaLogsRoute: typeof AuthenticatedLojaLogsRoute
  AuthenticatedLojaPedidosRoute: typeof AuthenticatedLojaPedidosRoute
  AuthenticatedLojaPrecificacaoRoute: typeof AuthenticatedLojaPrecificacaoRoute
  AuthenticatedLojaProdutosRoute: typeof AuthenticatedLojaProdutosRoute
  AuthenticatedLojaReceberRoute: typeof AuthenticatedLojaReceberRoute
  AuthenticatedLojaZonasEntregaRoute: typeof AuthenticatedLojaZonasEntregaRoute
  AuthenticatedLojaIndexRoute: typeof AuthenticatedLojaIndexRoute
  AuthenticatedLojaPedidoIdRoute: typeof AuthenticatedLojaPedidoIdRoute
}

const AuthenticatedLojaRouteChildren: AuthenticatedLojaRouteChildren = {
  AuthenticatedLojaChatRoute: AuthenticatedLojaChatRoute,
  AuthenticatedLojaConfigRoute: AuthenticatedLojaConfigRoute,
  AuthenticatedLojaDashboardRoute: AuthenticatedLojaDashboardRoute,
  AuthenticatedLojaEntregadoresRoute: AuthenticatedLojaEntregadoresRoute,
  AuthenticatedLojaFinanceiroRoute: AuthenticatedLojaFinanceiroRoute,
  AuthenticatedLojaFreteRoute: AuthenticatedLojaFreteRoute,
  AuthenticatedLojaLeadsRoute: AuthenticatedLojaLeadsRoute,
  AuthenticatedLojaLogsRoute: AuthenticatedLojaLogsRoute,
  AuthenticatedLojaPedidosRoute: AuthenticatedLojaPedidosRoute,
  AuthenticatedLojaPrecificacaoRoute: AuthenticatedLojaPrecificacaoRoute,
  AuthenticatedLojaProdutosRoute: AuthenticatedLojaProdutosRoute,
  AuthenticatedLojaReceberRoute: AuthenticatedLojaReceberRoute,
  AuthenticatedLojaZonasEntregaRoute: AuthenticatedLojaZonasEntregaRoute,
  AuthenticatedLojaIndexRoute: AuthenticatedLojaIndexRoute,
  AuthenticatedLojaPedidoIdRoute: AuthenticatedLojaPedidoIdRoute,
}

const AuthenticatedLojaRouteWithChildren =
  AuthenticatedLojaRoute._addFileChildren(AuthenticatedLojaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEntregadorRoute: typeof AuthenticatedEntregadorRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEntregadorRoute: AuthenticatedEntregadorRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  AdminLoginRoute: AdminLoginRoute,
  EntregadorLoginRoute: EntregadorLoginRoute,
  PedidoIdRoute: PedidoIdRoute,
  ApiPublicHooksSystemAlertsRoute: ApiPublicHooksSystemAlertsRoute,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRoute,
  ApiPublicWebhooksIfoodRoute: ApiPublicWebhooksIfoodRoute,
  ApiPublicWebhooksIfoodPollRoute: ApiPublicWebhooksIfoodPollRoute,
  ApiPublicWebhooksIfoodStatusPushRoute: ApiPublicWebhooksIfoodStatusPushRoute,
  ApiPublicWebhooksMetaRoute: ApiPublicWebhooksMetaRoute,
  ApiPublicWebhooksNfoodRoute: ApiPublicWebhooksNfoodRoute,
  ApiPublicWebhooksNfoodStatusPushRoute: ApiPublicWebhooksNfoodStatusPushRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicWebhooksWhatsappNotifyRoute: ApiPublicWebhooksWhatsappNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
